In [15]:
import pandas as pd
from pymongo import MongoClient
import re

In [19]:
def clean_text(text):
    cleaned_text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # Chuyển thành chữ thường
    cleaned_text = cleaned_text.lower()
    return cleaned_text

In [25]:
def extract_first_word(text):
    match = re.match(r'\b\w+\b', text)
    if match:
        return match.group(0)
    return None

In [8]:
client = MongoClient("mongodb+srv://testing_seg:nhatrinh269@cluster0.ui4yvfj.mongodb.net/")
db = client['disease_db_update']
disease_collection = db['disease']
link_collection = db['test1']

In [9]:
disease_data = disease_collection.find({})
link_data =  link_collection.find({})

In [10]:
disease_data_list = list(disease_data)
disease_df = pd.DataFrame(disease_data_list)
disease_df.head()

,_id,id_disease,Rare disease,attribute
0,666cce6bc049a13c960174ea,3be25fadac8eb4405fb2bc9e4ae8b62ae373e16305c0f9...,47 XXX (Trisomy X),"{'Disease': '47, XXX (Trisomy X) is a conditio..."
1,666cce6cc049a13c960174eb,8be09b21ec42da711adb7a2cc126d9632098c35c9f13ba...,47 XXY (Klinefelter Syndrome),"{'Disease': '47, XXY (Klinefelter Syndrome) is..."
2,666cce6cc049a13c960174ec,7b2017f6168f922c1ad6331e33aa3a4e9d08c77c2c406b...,48 XXYY Syndrome,"{'Disease': '48, XXYY Syndrome is a rare chrom..."
3,666cce6cc049a13c960174ed,2433940102def66bb4373962683874f7dca6fd3330fbf3...,5 10 – Methenyltetrahydrofolate Synthetase Def...,"{'Disease': '5,10-Methenyltetrahydrofolate Syn..."
4,666cce6cc049a13c960174ee,85659c2fe33e9d0b2bc45193e1169992976d5cb5871a05...,Aarskog Syndrome,{'Disease': 'Aarskog Syndrome is a genetic dis...

In [11]:
link_data_list = list(link_data)
link_df = pd.DataFrame(link_data_list)

attribute_df = link_df['attribute'].apply(pd.Series)
attribute_df.columns = ['Rare disease', 'type']
attribute_df['label'] = attribute_df['type'] + ' ' + attribute_df['Rare disease']

link_df = link_df.drop(columns=['attribute']).join(attribute_df)

link_df.head()

,_id,title,url,description,date,from,author,publication_date,Rare disease,type,label
0,6671c01e9f71f3d7b806ecf6,"47, XXX (Trisomy X) - Symptoms, Causes, Treatm...",rarediseases.org/rare-diseases/trisomy-x/,"47, XXX occurs randomly due to errors during t...",2024-04-4,National Organization for Rare Disorders,NaN,NaN,47 XXX (Trisomy X),Causes,Causes 47 XXX (Trisomy X)
1,6671c01e9f71f3d7b806ecf7,Trisomy X - Genetics,medlineplus.gov/genetics/condition/trisomy-x/,"Trisomy X, also called triple X syndrome or 47...",2022-02-28,MedlinePlus (.gov),NaN,NaN,47 XXX (Trisomy X),Causes,Causes 47 XXX (Trisomy X)
2,6671c01e9f71f3d7b806ecf8,"Triple X Syndrome: Causes, Diagnosis & Treatment",my.clevelandclinic.org/health/diseases/17892-t...,Triple X syndrome is a rare genetic condition ...,NaN,Cleveland Clinic,NaN,NaN,47 XXX (Trisomy X),Causes,Causes 47 XXX (Trisomy X)
3,6671c01e9f71f3d7b806ecf9,"A review of trisomy X (47,XXX)",ojrd.biomedcentral.com/articles/10.1186/1750-1...,Trích dẫn 389 bài viết — Trisomy X is a sex ch...,NaN,Orphanet Journal of Rare Diseases,NR Tartaglia,2010,47 XXX (Trisomy X),Causes,Causes 47 XXX (Trisomy X)
4,6671c01e9f71f3d7b806ecfa,Trisomy X,en.wikipedia.org/wiki/Trisomy_X,"Trisomy X, also known as triple X syndrome and...",NaN,Wikipedia,NaN,NaN,47 XXX (Trisomy X),Causes,Causes 47 XXX (Trisomy X)

In [12]:
label = []
description = []        

for index, i in link_df.iterrows():
    i["Rare disease"]
    for index, j in disease_df[:15].iterrows():
        if i["Rare disease"] == j["Rare disease"]:
            label.append(i["label"])
            description.append(clean_text(i["description"]))

sample_disease = pd.DataFrame({'label': label, 'description' : description})
sample_disease.head()

,label,description
0,Causes 47 XXX (Trisomy X),"47, XXX occurs randomly due to errors during t..."
1,Causes 47 XXX (Trisomy X),"Trisomy X, also called triple X syndrome or 47..."
2,Causes 47 XXX (Trisomy X),Triple X syndrome is a rare genetic condition ...
3,Causes 47 XXX (Trisomy X),Trích dẫn 389 bài viết — Trisomy X is a sex ch...
4,Causes 47 XXX (Trisomy X),"Trisomy X, also known as triple X syndrome and..."

# Model

In [ ]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [ ]:
import torch
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from transformers import BertTokenizer, BertForSequenceClassification, AdamW
from sklearn.metrics import classification_report
import numpy as np

In [ ]:
# Encode labels
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(sample_disease["label"])

# Split data into training and testing sets
train_texts, test_texts, train_labels, test_labels = train_test_split(
    sample_disease["description"], encoded_labels, test_size=0.2, random_state=42)

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(set(encoded_labels)))

# Prepare data
train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=128)

train_inputs = torch.tensor(train_encodings['input_ids'])
train_masks = torch.tensor(train_encodings['attention_mask'])
train_labels = torch.tensor(train_labels).long()  # Convert labels to LongTensor

test_inputs = torch.tensor(test_encodings['input_ids'])
test_masks = torch.tensor(test_encodings['attention_mask'])
test_labels = torch.tensor(test_labels).long()  # Convert labels to LongTensor

In [ ]:
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler

In [ ]:

batch_size = 16

train_data = TensorDataset(train_inputs, train_masks, train_labels)
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=batch_size)

test_data = TensorDataset(test_inputs, test_masks, test_labels)
test_sampler = SequentialSampler(test_data)
test_dataloader = DataLoader(test_data, sampler=test_sampler, batch_size=batch_size)

# Train model
optimizer = AdamW(model.parameters(), lr=2e-5)

model.train()
for epoch in range(50):  # Train for 3 epochs
    for batch in train_dataloader:
        batch_inputs, batch_masks, batch_labels = batch

        optimizer.zero_grad()
        outputs = model(batch_inputs, attention_mask=batch_masks, labels=batch_labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()

# Evaluate model
model.eval()
predictions, true_labels = [], []

for batch in test_dataloader:
    batch_inputs, batch_masks, batch_labels = batch

    with torch.no_grad():
        outputs = model(batch_inputs, attention_mask=batch_masks)
        logits = outputs.logits

    predictions.extend(torch.argmax(logits, axis=1).tolist())
    true_labels.extend(batch_labels.tolist())

target_names = list(map(str, label_encoder.classes_))
print(classification_report(true_labels, predictions, target_names=target_names, labels=np.unique(true_labels)))

# Function to classify new text
def classify_text(text, model, tokenizer, label_encoder):
    model.eval()
    encodings = tokenizer(text, truncation=True, padding=True, max_length=128, return_tensors='pt')
    input_ids = encodings['input_ids']
    attention_mask = encodings['attention_mask']
    
    with torch.no_grad():
        outputs = model(input_ids, attention_mask=attention_mask)
        logits = outputs.logits
    
    predicted_label_id = torch.argmax(logits, axis=1).item()
    predicted_label = label_encoder.inverse_transform([predicted_label_id])[0]
    return predicted_label

In [13]:
import language_tool_python
from autocorrect import Speller

def correct_spelling_and_grammar(text):
    # Khởi tạo đối tượng kiểm tra chính tả và ngữ pháp
    spell = Speller(lang='en')
    tool = language_tool_python.LanguageTool('en-US')
    # Sửa lỗi chính tả
    corrected_text = spell(text)
    # Sửa lỗi ngữ pháp
    matches = tool.check(corrected_text)
    corrected_text = language_tool_python.utils.correct(corrected_text, matches)
    
    return corrected_text

I have a spelling error in this sentence and it is a grammatical error.

In [1]:
from sentence_transformers import SentenceTransformer, util
import pandas as pd

def find_similar_documents(sample_test, query_non_ai, model_name='all-MiniLM-L6-v2'):
    # Tải mô hình Sentence Transformers
    model = SentenceTransformer(model_name)

    # Mã hóa các đoạn văn bản và đoạn query
    embeddings = model.encode(sample_test + [query_non_ai])

    # Tính toán độ tương đồng cosine giữa query và các đoạn văn bản
    query_embedding = embeddings[-1]
    doc_embeddings = embeddings[:-1]
    cosine_similarities = util.pytorch_cos_sim(query_embedding, doc_embeddings)[0]

    # Sắp xếp các đoạn văn bản theo độ tương đồng giảm dần
    sorted_indices = cosine_similarities.argsort(descending=True)
    sorted_documents = [sample_test[i] for i in sorted_indices]
    sorted_similarities = [cosine_similarities[i].item() for i in sorted_indices]

    # Tạo DataFrame kết quả
    result_df = pd.DataFrame({
        'Document': sorted_documents,
        'Similarity': sorted_similarities
    })

    return result_df

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

             Document  Similarity
0  Đoạn văn bản mẫu 1    0.728959
1  Đoạn văn bản mẫu 2    0.721913
2  Đoạn văn bản mẫu 3    0.712987

In [20]:
# Causes Abetalipoproteinemia
# caused by mutations in the gene encoding MTP, a protein that transfers lipids to apoB in the ER, forming nascent chylomicrons and VLDL in the intestine and liver, respectively.

test_documents = "caed by mutats in the gne encoding MTP, a prtein that transfers lipids to apB in the ER, forming nascent chylomicrons and VLDL in the iestine and lver, respectively."

documents_error_correction = correct_spelling_and_grammar(test_documents)

label = classify_text(clean_text(test_documents), model, tokenizer, label_encoder)

type_disease = extract_first_word(label)
disaese = label.replace(type_disease, "").strip()

results = link_collection.find({
    "$and": [
        {"attribute.Rare disease": disaese},
        {"attribute.type": type_disease}
    ],
},
    {
    "_id": 0
})

results_list = list(results)
df = pd.DataFrame(results_list)

find_similar_documents(results_list["description"], documents_error_correction)

['MD is an inherited condition card by genetic plants (changes in your genes). The changes can alter certain processes in your body and result in disease. The gene involved in MD is called MP1. The role of MP1 is to make an enzyme called acid sphingomyelinase (skin-go-my-uh-Lin-ase), or SM.',
 'Rare disorder that occurs primarily in postmenopausal women and is characterized by type 2 (insulin-resistant) diabetes mellitus and signs of androgen excess. The exact cause of this syndrome is unknown.',
 'A rare disorder that occurs primarily in menopausal women and is characters by type 2 (insulin-resistant) diabetes mellitus and signs of androgen excess. The exact cause of this syndrome is unknown.']

In [ ]:
# Complications 47 XXX (Trisomy X)
# tend to develop diabetes, chronic lung disease, varicose veins, hypothyroidism and breast cancer more often than other men. Mosaicism occurs in about 15 of cases.

test_documents = "tend to delop diabetes, chronic lg disease, varicose veins, hypothyrdism and breast cacer more oen than other men. Mosaicm occurs in about 15 of cases."

documents_error_correction = correct_spelling_and_grammar(test_documents)

label = classify_text(clean_text(test_documents), model, tokenizer, label_encoder)

type_disease = extract_first_word(label)
disaese = label.replace(type_disease, "").strip()

results = link_collection.find({
    "$and": [
        {"attribute.Rare disease": disaese},
        {"attribute.type": type_disease}
    ],
},
    {
    "_id": 0
})

results_list = list(results)
df = pd.DataFrame(results_list)

find_similar_documents(results_list["description"], documents_error_correction)

In [ ]:
# Prevention 47 XXX (Trisomy X)
# occurs randomly due to errors during the division of reproductive cells in one of the parents.

test_documents = "occurs ranmly due to eors during the division of repductive cels in one of the parents."

documents_error_correction = correct_spelling_and_grammar(test_documents)

label = classify_text(clean_text(test_documents), model, tokenizer, label_encoder)

type_disease = extract_first_word(label)
disaese = label.replace(type_disease, "").strip()

results = link_collection.find({
    "$and": [
        {"attribute.Rare disease": disaese},
        {"attribute.type": type_disease}
    ],
},
    {
    "_id": 0
})

results_list = list(results)
df = pd.DataFrame(results_list)

find_similar_documents(results_list["description"], documents_error_correction)